name: hydropy
dependencies:
- cairo=1.12.18=4
- certifi=14.05.14=py27_0
- decorator=4.0.2=py27_0
- fontconfig=2.11.1=4
- freetype=2.5.2=2
- ipykernel=4.0.3=py27_0
- ipython=4.0.0=py27_0
- ipython-notebook=4.0.4=py27_0
- ipython_genutils=0.1.0=py27_0
- jinja2=2.8=py27_0
- jsonschema=2.4.0=py27_0
- jupyter_client=4.0.0=py27_0
- jupyter_core=4.0.4=py27_0
- libgfortran=1.0=0
- libpng=1.6.17=0
- libsodium=0.4.5=0
- libxml2=2.9.2=0
- markupsafe=0.23=py27_0
- matplotlib=1.4.3=np19py27_2
- mistune=0.7.1=py27_0
- nbconvert=4.0.0=py27_0
- nbformat=4.0.0=py27_0
- notebook=4.0.4=py27_0
- numpy=1.9.2=py27_2
- openblas=0.2.14=2
- openssl=1.0.1k=1
- pandas=0.16.2=np19py27_0
- path.py=7.6.1=py27_0
- pexpect=3.3=py27_0
- pickleshare=0.5=py27_0
- pixman=0.26.2=0
- ptyprocess=0.4=py27_0
- py2cairo=1.10.0=py27_2
- pygments=2.0.2=py27_0
- pyparsing=2.0.3=py27_0
- pyqt=4.11.3=py27_1
- python=2.7.10=1
- python-dateutil=2.4.2=py27_0
- pytz=2015.4=py27_0
- pyzmq=14.7.0=py27_0
- qt=4.8.6=3
- readline=6.2=2
- scipy=0.16.0=np19py27_1
- seaborn=0.6.0=np19py27_0
- setuptools=18.1=py27_0
- simplegeneric=0.8.1=py27_0
- sip=4.16.5=py27_0
- six=1.9.0=py27_0
- sqlite=3.8.4.1=1
- ssl_match_hostname=3.4.0.2=py27_0
- terminado=0.5=py27_0
- tk=8.5.18=0
- tornado=4.2.1=py27_0
- traitlets=4.0.0=py27_0
- zeromq=4.0.5=0
- zlib=1.2.8=0

